#!/bin/bash
SHMALL_MEM=`/sbin/sysctl -n kernel.shmall`
SHMALL_MIN=4294967296
if [ "$SHMALL_MEM" -lt $SHMALL_MIN ]
then
    echo "Setting SHMALL to ${SHMALL_MIN}"
    /sbin/sysctl -w kernel.shmall=$SHMALL_MIN
fi

SHMMAX_MEM=`/sbin/sysctl -n kernel.shmmax`
SHMMAX_MIN=1073741824
if [ "$SHMMAX_MEM" -lt $SHMMAX_MIN ]
then
    echo "Setting SHMMAX to ${SHMMAX_MIN}"
    /sbin/sysctl -w kernel.shmmax=$SHMMAX_MIN
fi

if [ -f /etc/aerospike/initfns ]
then
    . /etc/aerospike/initfns
fi